### ISSUE TITLE
The tool not exporting certain commu.json files, mainly commus using the "99" IDs

### ISSUE THREAD

**Issue by ToastyBuns3939** [chinosk6/scsp-localify#10]
![image](https://github.com/chinosk6/scsp-localify/assets/93896872/184cde9f-27a0-492d-8554-69bc1dbc0f57)
![image](https://github.com/chinosk6/scsp-localify/assets/93896872/f9e786de-20dc-4fc9-a8f9-aa0bcf618c9f)

![image](https://github.com/chinosk6/scsp-localify/assets/93896872/a7c8a5b9-e56c-41bf-8b22-06b406d573bd)
![image](https://github.com/chinosk6/scsp-localify/assets/93896872/7fff805d-789e-45a2-bdbf-da7f5acbf3ad)

I am currently translating the latest event story and i just realized the your tool forgot to dump the epilogue chapters.
the file for the epilogue chapter for the latest event should be called `s42_01010100_99.json`

**Comment by chinosk6** [comment]
fixed. binary test files [here](../actions/runs/8506411478)
