### ISSUE TITLE
I don't know how to make the same idol appear in a live MV

### ISSUE THREAD

**Issue by namenemeko** [chinosk6/scsp-localify#13]
What steps are required after enabling "Live Allow Same Idol"?

**Comment by chinosk6** [comment]
After the game update, this feature is no longer functioning. I'll try to fix it.

**Comment by namenemeko** [comment]
If you enable "Live Allow Same Idol" and "Live Unlock All Dress" and change the costume with the same idol selected, everyone's costume will change.
Furthermore, if you disable "Live Unlock All Dress" from this state, you can now select all costumes.

**Comment by chinosk6** [comment]
`Live Unlock All Dress` is a safe mode that change the `ResourceId` of the default costume, then upload the default costume ID to game server. 
The same character used the same default costume, so this issue occurred.
