### ISSUE TITLE
is it possible to add a feature where you can unlock card commus?

### ISSUE THREAD

**Issue by ToastyBuns3939** [chinosk6/scsp-localify#20]
![image](https://github.com/chinosk6/scsp-localify/assets/93896872/f5e6fc6d-4960-4c32-be00-574d12eccac5)

Since the produce and support idol commus only shows up randomly on produce run, it makes them extra hard to proofread for translation purposes. You can't even unlock them via auto produces.

**Comment by chinosk6** [comment]
Now you can unlock `Idol Events` and `Support Events` by checking this option.
![image](https://github.com/chinosk6/scsp-localify/assets/74499927/81fd7b46-3cea-46f6-998e-2f5cb052b3b0)
