### ISSUE TITLE
Is it possible to add the feature to dump ResourceVersion in a format like 10002410@wlSP3H1TCIRn+z0SwFG8a+s=?

### ISSUE THREAD

**Issue by Sheep975** [chinosk6/scsp-localify#22]

**Comment by chinosk6** [comment]
Do you only need strings like this `10003100@XENts3gETsFn7hGP/lxMVKk=` ?

**Comment by chinosk6** [comment]
This has already been implemented in #8 , now all we need to do is add a print.
https://github.com/chinosk6/scsp-localify/blob/f6c5e6f57642f3076961b48f307d7022fbd36dc9/src/hook.cpp#L934-L935

**Comment by chinosk6** [comment]
Now version info will be output at game startup.
test binary files [here](../actions/runs/9034421870)
![image](https://github.com/chinosk6/scsp-localify/assets/74499927/5fa81090-1601-47f0-8db2-3406a88f8114)

**Comment by Sheep975** [comment]
It worked perfectly! Thank you again!!
