### ISSUE TITLE
An issue with the new limited utaiwake feature not working when the same idols are selected in one song.

### ISSUE THREAD

**Issue by ToastyBuns3939** [chinosk6/scsp-localify#24]
![image](https://github.com/chinosk6/scsp-localify/assets/93896872/b8d36917-2a67-44f4-ab7c-e4863dfa0371)
![image](https://github.com/chinosk6/scsp-localify/assets/93896872/71234ea1-5333-42b7-b0e1-9ee574793949)

it just falls back to the default version when the same idols are chosen instead of going with the same vocal tracks for each positions.

**Comment by chinosk6** [comment]
Resolved: [Actions](../actions/runs/9990580455)
![image](https://github.com/user-attachments/assets/4094c9c0-2afc-45b8-9345-9de7be511693)
