### ISSUE TITLE
Text extracting doesn't work

### ISSUE THREAD

**Issue by ToastyBuns3939** [chinosk6/scsp-localify#27]
![image](https://github.com/chinosk6/scsp-localify/assets/93896872/4e57e3fb-5b2d-41d1-b21f-0d32cf130ab3)
![image](https://github.com/chinosk6/scsp-localify/assets/93896872/816a2d41-ffdb-4493-9931-11dcd7d346e9)
got this error when trying to dump a new batch of text files

**Comment by chinosk6** [comment]
fixed. see: [Actions](../actions/runs/9436829650)
