### ISSUE TITLE
An error is occurring when building

### ISSUE THREAD

**Issue by namenemeko** [chinosk6/scsp-localify#3]
I'm getting the error "'MH_StatusToString': Identifier not found" in hook.cpp
I think that minhook has probably not been installed properly, but how can I solve this?

**Comment by chinosk6** [comment]
You can follow the steps in [ci.yml](../blob/main/.github/workflows/ci.yml).

**Comment by chinosk6** [comment]
or your submodule has not been initialized
```shell
git submodule update --init
```

**Comment by namenemeko** [comment]
The build went well. Thank you very much.

By the way, not related to this issue, but you can disable nProtect using this tool: https://github.com/Kimjio/imas-sc-prism-localify
It may be useful for your development.
