### ISSUE TITLE
scsp-config.json is not loaded.

### ISSUE THREAD

**Issue by coiru** [chinosk6/scsp-localify#31]
The settings in scsp-config.json are not reflected in the game.

**Comment by chinosk6** [comment]
Please provide more information.

**Comment by coiru** [comment]
Even if you change the settings in scsp-config.json, they will not be reflected when you start the game.
All values ​​will be default.
The saved SwayStringOffset value will be reflected.

**Comment by chinosk6** [comment]
Sorry, I still can't understand your question. Can you please answer the following questions?
 - What files are in your directory?
 - What configuration do you want to change?
 - What are your steps?
 - What is the content of your `scsp-config.json` file?

**Comment by coiru** [comment]
Sorry, I checked scsp-config.json and found that the description was incorrect. (A "," was missing.)
The settings are now reflected correctly.
