### ISSUE TITLE
Some functions fail to inject after 1.9.0 update

### ISSUE THREAD

**Issue by 11-59pm** [chinosk6/scsp-localify#32]
![image](https://github.com/user-attachments/assets/d9ecd54c-9703-44f5-afac-6ee49cf23a26)

![image](https://github.com/user-attachments/assets/f06569b5-c017-431a-804f-96d84cfcd4cf)

Functionalities such as Freecam does not work.

Looks like the assembly has changed.

**Comment by chinosk6** [comment]
Fixed: [Actions](../actions/runs/9988764542)

**Comment by 11-59pm** [comment]
Thank you so much!
