### ISSUE TITLE
Character's breasts do not shake.

### ISSUE THREAD

**Issue by namenemeko** [chinosk6/scsp-localify#4]
If "enableVSync" is set to true, the character's breasts will shake less.
It varies from costume to costume, but in most cases it is smaller than the original.

**Comment by chinosk6** [comment]
Maybe it caused by the game's frame rate, like uma-musume?

**Comment by namenemeko** [comment]
Sorry, I solved the problem myself.
I set VSync to "Use App Settings" in the VIDIA Control Panel and the problem no longer occurs.
